In [1]:
import numpy as np
import pandas as pd

In [2]:
def read_file(path,extension,blank_firstrow=False):
    if extension == 'csv':
        if blank_firstrow:
            df = pd.read_csv(path, sep = ';', skiprows = 1, escapechar='\n')
        else:
            df = pd.read_csv(path, sep = ';', escapechar='\n')
    elif extension == 'txt':
        df = pd.read_csv(path, sep = '\t')
    elif extension == 'xls':
        df = pd.read_excel(path, skiprows = 1)
    return df

In [3]:
df_edu = read_file('../data/csv/education.csv','csv',True)
df_reg = read_file('../data/csv/region.txt','txt')
df_area = read_file('../data/csv/area.csv','csv')
df_exp = read_file('../data/csv/life_expectancy.csv','csv')
df_crime = read_file('../data/csv/crime.csv','csv')
df_income = read_file('../data/csv/income.xls','xls',True)

In [4]:
df_edu

,"State,federal district,or territory",% High school graduateor higher,High School rank,% Bachelor's degreeor higher,Bachelor's rank,% Advanced degree,Advanced rank
0,Montana,93.0%,1.0,30.7%,21.0,10.1%,33.0
1,New Hampshire,92.8%,2.0,36.0%,9.0,13.8%,10.0
2,Minnesota,92.8%,3.0,34.8%,11.0,11.8%,18.0
3,Wyoming,92.8%,4.0,26.7%,41.0,9.3%,39.0
4,Alaska,92.4%,5.0,29.0%,28.0,10.4%,29.0
5,North Dakota,92.3%,6.0,28.9%,29.0,7.8%,51.0
6,Vermont,92.3%,7.0,36.8%,8.0,15.0%,7.0
7,Maine,92.1%,8.0,30.3%,23.0,10.9%,24.0
8,Iowa,91.8%,9.0,27.7%,36.0,9.0%,42.0
9,Utah,91.8%,10.0,32.5%,16.0,11.0%,23.0
10,Wisconsin,91.7%,11.0,29.0%,27.0,9.9%,35.0
11,Hawaii,91.6%,12.0,32.0%,19.0,10.8%,25.0
12,South Dakota,91.4%,13.0,27.8%,35.0,8.3%,45.0
13,Colorado,91.1%,14.0,39.4%,3.0,14.6%,9.0
14,Nebraska,90.9%,15.0,30.6%,22.0,10.2%,31.0
15,Washington,90.8%,16.0,34.5%,12.0,12.7%,14.0
16,Kansas,90.5%,17.0,32.3%,17.0,11.7%,20.0
17,District of Columbia,90.3%,18.0,56.6%,1.0,32.8%,1.0
18,Massachusetts,90.3%,19.0,42.1%,2.0,18.7%,2.0
19,Idaho,90.2%,20.0,26.8%,40.0,8.5%,43.0
20,Michigan,90.2%,21.0,28.1%,34.0,11.0%,22.0
21,Connecticut,90.2%,22.0,38.4%,5.0,17.0%,4.0
22,Oregon,76.7%,23.0,32.3%,18.0,12.2%,16.0
23,Pennsylvania,89.9%,24.0,30.1%,24.0,11.8%,19.0
24,Maryland,89.8%,25.0,39.0%,4.0,18.0%,3.0
25,Ohio,89.8%,26.0,27.2%,37.0,10.2%,32.0
26,Delaware,89.3%,27.0,31.0%,20.0,12.9%,13.0
27,Missouri,89.2%,28.0,28.2%,33.0,10.7%,26.0
28,New Jersey,89.2%,29.0,38.1%,6.0,14.7%,8.0
29,Virginia,89.0%,30.0,37.6%,7.0,16.1%,5.0
30,Illinois,88.6%,31.0,33.4%,13.0,13.0%,12.0
31,Indiana,88.3%,32.0,25.3%,43.0,9.2%,40.0
32,Florida,87.6%,33.0,28.5%,31.0,10.3%,30.0
33,Oklahoma,87.5%,34.0,24.8%,44.0,8.3%,44.0
34,Rhode Island,87.3%,35.0,33.0%,14.0,13.1%,11.0
35,United States,87.3%,35.5,30.9%,20.5,11.8%,18.5
36,North Carolina,86.9%,36.0,29.9%,26.0,10.6%,28.0
37,South Carolina,86.5%,37.0,27.0%,38.0,9.8%,36.0
38,Tennessee,86.5%,38.0,26.1%,42.0,9.6%,37.0
39,Georgia,86.3%,39.0,29.9%,25.0,11.4%,21.0
40,New York,86.1%,40.0,35.3%,10.0,15.4%,6.0
41,West Virginia,85.9%,41.0,19.9%,51.0,7.9%,49.0
42,Nevada,85.8%,42.0,23.7%,46.0,8.1%,47.0
43,Arkansas,85.6%,43.0,22.0%,49.0,7.9%,50.0
44,Alabama,85.3%,44.0,24.5%,45.0,9.1%,41.0
45,Kentucky,85.2%,45.0,23.2%,48.0,9.6%,38.0
46,New Mexico,85.0%,46.0,26.9%,39.0,11.8%,17.0
47,Louisiana,84.3%,47.0,23.4%,47.0,8.1%,46.0
48,Mississippi,83.4%,48.0,21.3%,50.0,8.0%,48.0
49,Texas,82.8%,49.0,28.7%,30.0,9.9%,34.0
50,California,82.5%,50.0,32.6%,15.0,12.2%,15.0
51,Arizona,82.1%,51.0,28.4%,32.0,10.7%,26.0

In [5]:
df_reg

              Name Abb         Region            Division
1          Alabama  AL          South  East South Central
2           Alaska  AK           West             Pacific
3          Arizona  AZ           West            Mountain
4         Arkansas  AR          South  west south central
5       California  CA           West             Pacific
6         Colorado  CO           West            Mountain
7      Connecticut  CT      Northeast         New England
8         Delaware  DE          South      south atlantic
9          Florida  FL          South      South Atlantic
10         Georgia  GA          South      South Atlantic
11          Hawaii  HI           West             Pacific
12           Idaho  ID           West            Mountain
13        Illinois  IL  North Central  East North Central
14         Indiana  IN  North Central  East North Central
15            Iowa  IA  North Central  West North Central
16          Kansas  KS  North Central  West North Central
17        Kentucky  KY          South  East South Central
18       Louisiana  LA          South  West South Central
19           Maine  ME      Northeast         New England
20        Maryland  MD          South      South Atlantic
21   Massachusetts  MA      Northeast         New England
22        Michigan  MI  North Central  East North Central
23       Minnesota  MN  North Central  West North Central
24     Mississippi  MS          South  East South Central
25        Missouri  MO  North Central  West North Central
26         Montana  MT           West            Mountain
27        Nebraska  NE  North Central  West North Central
28          Nevada  NV           West            Mountain
29   New Hampshire  NH      Northeast         New England
30      New Jersey  NJ      Northeast     Middle Atlantic
31      New Mexico  NM           West            Mountain
32        New York  NY      Northeast     Middle Atlantic
33  North Carolina  NC          South      South Atlantic
34    North Dakota  ND  North Central  West North Central
35            Ohio  OH  North Central  East North Central
36        Oklahoma  OK          South  West South Central
37          Oregon  OR           West             Pacific
38    Pennsylvania  PA      Northeast     Middle Atlantic
39    Rhode Island  RI      Northeast         New England
40  South Carolina  SC          South      South Atlantic
41    South Dakota  SD  North Central  West North Central
42       Tennessee  TN          South  East South Central
43           Texas  TX          South  West South Central
44            Utah  UT           West            Mountain
45         Vermont  VT      Northeast         New England
46        Virginia  VA          South      South Atlantic
47      Washington  WA           West             Pacific
48   West Virginia  WV          South      South Atlantic
49       Wisconsin  WI  North Central  East North Central
50         Wyoming  WY           West            Mountain

In [6]:
df_area

,State,TotalRank,TotalSqMi,TotalKmQ,LandRank,LandSqMi,LandKmQ,LandPer,WaterRank,WaterSqMi,WaterKmQ,WaterPer
0,Alaska,1,665384.04,1723337,1,570640.95,1477953,85.76,1,94743.10,245384,14.24
1,Texas,2,268596.46,695662,2,261231.71,676587,97.26,8,7364.75,19075,2.74
2,California,3,163694.74,423967,3,155779.22,403466,95.16,6,7915.52,20501,4.84
3,Montana,4,147039.71,380831,4,145545.80,376962,98.98,26,1493.91,3869,1.02
4,New Mexico,5,121590.30,314917,5,121298.15,314161,99.76,49,292.15,757,0.24
5,Arizona,6,113990.30,295234,6,113594.08,294207,99.65,48,396.22,1026,0.35
6,Nevada,7,110571.82,286380,7,109781.18,284332,99.28,36,790.65,2048,0.72
7,Colorado,8,104093.67,269601,8,103641.89,268431,99.57,44,451.78,1170,0.43
8,Oregon,9,98378.54,254799,10,95988.01,248608,97.57,20,2390.53,6191,2.43
9,Wyoming,10,97813.01,253335,9,97093.14,251470,99.26,37,719.87,1864,0.74
10,Michigan,11,96713.51,250487,22,56538.90,146435,58.46,2,40174.61,104052,41.54
11,Minnesota,12,86935.83,225163,14,79626.74,206232,91.59,9,7309.09,18930,8.41
12,Utah,13,84896.88,219882,12,82169.62,212818,96.79,17,2727.26,7064,3.21
13,Idaho,14,83568.95,216443,11,82643.12,214045,98.89,33,925.83,2398,1.11
14,Kansas,15,82278.36,213100,13,81758.72,211754,99.37,42,519.64,1346,0.63
15,Nebraska,16,77347.81,200330,15,76824.17,198974,99.32,41,523.64,1356,0.68
16,South Dakota,17,77115.68,199729,16,75811.00,196350,98.31,29,1304.68,3379,1.69
17,Washington,18,71297.95,184661,20,66455.52,172119,93.21,11,4842.43,12542,6.79
18,North Dakota,19,70698.32,183108,17,69000.80,178711,97.60,24,1697.52,4397,2.40
19,Oklahoma,20,69898.87,181037,19,68594.92,177660,98.13,30,1303.95,3377,1.87
20,Missouri,21,69706.99,180540,18,68741.52,178040,98.61,32,965.47,2501,1.39
21,Florida,22,65757.70,170312,26,53624.76,138887,81.55,3,12132.94,31424,18.45
22,Wisconsin,23,65496.38,169635,25,54157.80,140268,82.69,4,11338.57,29367,17.31
23,Georgia,24,59425.15,153910,21,57513.49,148959,96.78,22,1911.66,4951,3.22
24,Illinois,25,57913.55,149995,24,55518.93,143793,95.87,19,2394.62,6202,4.13
25,Iowa,26,56272.81,145746,23,55857.13,144669,99.26,45,415.68,1077,0.74
26,New York,27,54554.98,141297,30,47126.40,122057,86.38,7,7428.58,19240,13.62
27,North Carolina,28,53819.16,139391,29,48617.91,125920,90.34,10,5201.25,13471,9.66
28,Arkansas,29,53178.55,137732,27,52035.48,134771,97.85,31,1143.07,2961,2.15
29,Alabama,30,52420.07,135767,28,50645.33,131171,96.61,23,1774.74,4597,3.39
30,Louisiana,31,52378.13,135659,33,43203.90,111898,82.48,5,9174.23,23761,17.52
31,Mississippi,32,48431.78,125438,31,46923.27,121531,96.89,25,1508.51,3907,3.11
32,Pennsylvania,33,46054.34,119280,32,44742.70,115883,97.15,28,1311.64,3397,2.85
33,Ohio,34,44825.58,116098,35,40860.69,105829,91.15,14,3964.89,10269,8.85
34,Virginia,35,42774.93,110787,36,39490.09,102279,92.32,15,3284.84,8508,7.68
35,Tennessee,36,42144.25,109153,34,41234.90,106798,97.84,35,909.36,2355,2.16
36,Kentucky,37,40407.80,104656,37,39486.34,102269,97.72,34,921.46,2387,2.28
37,Indiana,38,36419.55,94326,38,35826.11,92789,98.37,39,593.44,1537,1.63
38,Maine,39,35379.74,91633,39,30842.92,79883,87.18,12,4536.82,11750,12.82
39,South Carolina,40,32020.49,82933,40,30060.70,77857,93.88,21,1959.79,5076,6.12
40,West Virginia,41,24230.04,62756,41,24038.21,62259,99.21,50,191.83,497,0.79
41,Maryland,42,12405.93,32131,42,9707.24,25142,78.25,18,2698.69,6990,21.75
42,Hawaii,43,10931.72,28313,47,6422.63,16635,58.75,13,4509.09,11678,41.25
43,Massachusetts,44,10554.39,27336,45,7800.06,20202,73.90,16,2754.33,7134,26.10
44,Vermont,45,9616.36,24906,43,9216.66,23871,95.84,46,399.71,1035,4.16
45,New Hampshire,46,9349.16,24214,44,8952.65,23187,95.76,47,396.51,1027,4.24
46,New Jersey,47,8722.58,22591,46,7354.22,19047,84.31,27,1368.36,3544,15.69
47,Connecticut,48,5543.41,14357,48,4842.36,12542,87.35,38,701.06,1816,12.65
48,Delaware,49,2488.72,6446,49,1948.54,5047,78.29,40,540.18,1399,21.71
49,Rhode Island,50,1544.89,4001,50,1033.81,2678,66.92,43,511.07,1324,33.08

In [7]:
df_exp

,State,LifeExp2018,LifeExp2010,MaleLifeExp,FemLifeExp
0,Hawaii,82.3,81.4,79.3,85.3
1,California,81.6,80.6,79.4,83.8
2,Puerto Rico,81.3,78.7,77.6,84.7
3,New York,81.3,80.3,79.0,83.4
4,U.S. Virgin Islands,81.2,79.2,76.3,85.6
5,Minnesota,81.0,80.8,79.0,83.0
6,Connecticut,80.9,80.7,78.7,83.0
7,Guam,80.7,78.2,77.6,83.8
8,Colorado,80.5,80.1,78.5,82.5
9,Massachusetts,80.5,80.5,78.2,82.6
10,Washington,80.4,80.1,78.4,82.4
11,New Jersey,80.4,80.0,78.2,82.5
12,Florida,80.0,79.0,77.3,82.6
13,Arizona,79.9,79.3,77.5,82.3
14,Rhode Island,79.9,79.5,77.7,82.1
15,North Dakota,79.9,79.7,77.6,82.5
16,Utah,79.9,79.8,78.2,81.6
17,Oregon,79.8,79.5,77.8,81.9
18,Vermont,79.7,80.1,77.8,81.7
19,Nebraska,79.6,79.7,77.4,81.7
20,Virginia,79.5,79.1,77.4,81.5
21,New Hampshire,79.5,80.3,77.5,81.4
22,Iowa,79.4,79.6,77.2,81.6
23,Wisconsin,79.4,79.6,77.3,81.5
24,Illinois,79.3,79.0,77.0,81.6
25,Idaho,79.3,79.4,77.4,81.2
26,Texas,79.1,78.4,76.8,81.5
27,Maryland,79.1,79.0,76.7,81.4
28,South Dakota,79.1,79.3,76.7,81.6
29,Wyoming,79.0,78.1,77.1,81.1
30,Alaska,78.8,78.0,76.7,81.2
31,Montana,78.8,78.5,76.8,81.0
32,United States,78.7[17],78.7,76.2,81.2
33,Maine,78.7,79.1,76.6,81.0
34,District of Columbia,78.6,76.5,75.7,81.3
35,Nevada,78.5,77.8,76.1,81.0
36,Kansas,78.5,78.6,76.3,80.7
37,Delaware,78.4,78.3,76.2,80.6
38,Pennsylvania,78.3,78.5,75.8,80.6
39,New Mexico,78.1,78.2,75.3,81.0
40,North Carolina,78.0,77.8,75.5,80.3
41,Michigan,78.0,78.0,75.7,80.2
42,Georgia,77.8,77.3,75.4,80.0
43,Missouri,77.3,77.4,74.9,79.8
44,South Carolina,77.0,76.8,74.4,79.6
45,Indiana,77.0,77.5,74.6,79.3
46,Ohio,76.9,77.7,74.6,79.2
47,Northern Mariana Islands,76.4,76.9,73.6,79.3
48,Louisiana,76.1,75.8,73.4,79.0
49,Oklahoma,76.0,75.7,73.7,78.4
50,Tennessee,76.0,76.2,73.3,78.6
51,Arkansas,75.9,76.0,73.1,78.6
52,Alabama,75.4,75.4,72.6,78.1
53,Kentucky,75.4,75.9,72.8,77.9
54,Mississippi,74.9,74.8,71.9,78.0
55,American Samoa,74.8,74.0,73.0,77.0
56,West Virginia,74.8,75.5,72.4,77.4

In [8]:
df_crime

,State,Population(total inhabitants) (2015) [2],Murders andNonnegligentManslaughter(total deaths) (2015) [1],Murders(total deaths) (2015) [3],Gun Murders(total deaths) (2015) [3],GunOwnership(%) (2013) [4],"Murder andNonnegligentManslaughterRate(per 100,000) (2015)","Murder Rate(per 100,000) (2015)","GunMurder Rate(per 100,000) (2015)"
0,Alabama,"4,853,875",348,—[a],—[a],48.9,7.2,— [a],— [a]
1,Alaska,"737,709",59,57,39,61.7,8.0,7.7,5.3
2,Arizona,"6,817,565",306,278,171,32.3,4.5,4.1,2.5
3,Arkansas,"2,977,853",181,164,110,57.9,6.1,5.5,3.7
4,California,"38,993,940","1,861","1,861","1,275",20.1,4.8,4.8,3.3
...,...,...,...,...,...,...,...,...,...
57,b,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
59,c,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,d,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df_income

,Rank,State,Income2017,Income2016,Income2015,Income2014,Income2013,Income2012,Income2011,Income2010,Income2009,Income2008,Income2007
0,1,District of Columbia,82336,75506,75628,71648,67572,65246,66583,63124,59290,57936,54317
1,2,Maryland,80776,78945,75847,73971,72483,71836,70004,68854,69272,70545,68080
2,3,New Jersey,80088,76126,72222,72919,70165,69667,67458,67681,68342,70373,67035
3,4,Hawaii,77765,74511,73486,69592,68020,66259,61821,63030,64098,67214,63746
4,5,Massachusetts,77385,75297,70628,69160,66768,65339,62859,62072,64081,65401,62365
5,6,Connecticut,74168,73433,71346,70048,67098,67276,65753,64032,67034,68595,65967
6,7,New Hampshire,73381,70936,70303,66532,64230,63280,62647,61042,60567,63731,62369
7,8,Alaska,73181,76440,73355,71583,72237,67712,67825,64576,66953,68460,64333
8,9,California,71805,67739,64500,61933,60190,58328,57287,57708,58931,61021,59948
9,10,Virginia,71535,68114,66262,64902,62666,61741,61882,60674,59330,61233,59562
10,11,Washington,70979,67106,64129,61366,58405,57573,56835,55631,56548,58078,55212
11,12,Colorado,69117,65685,63909,61303,58823,56765,55387,54046,55430,56993,55212
12,13,Minnesota,68388,65599,63488,61481,60702,58906,56954,55459,55616,57288,55802
13,14,Utah,68358,65977,62912,60922,59770,57049,55869,54744,55117,56633,55109
14,15,New York,64894,62909,60850,58878,57369,56448,55246,54148,54659,56013,53514
15,16,Rhode Island,63870,60596,58073,54891,55902,54554,53636,52254,54119,55701,53568
16,17,Illinois,62992,60960,59588,57444,56210,55137,53234,52972,53966,56235,54124
17,18,Delaware,62852,61757,61255,59716,57846,54554,58814,55847,56860,57989,54610
18,19,North Dakota,61843,60656,60557,59029,55759,53585,51704,48670,47827,46032,43531
19,20,Wyoming,60434,59882,60214,57055,58752,54901,56322,53512,52664,53207,51731
20,21,Oregon,60212,57532,54148,51075,50251,49161,46816,46560,48457,50169,48730
21,22,Nebraska,59970,56927,54996,52686,51440,50723,50296,52504,48408,49693,47085
22,23,Wisconsin,59305,56811,55638,52622,51467,51059,50395,49001,49993,52094,50578
23,24,Texas,59206,56565,55653,53035,51704,50740,49392,48615,48259,50043,47548
24,25,Pennsylvania,59195,56907,55702,53234,52007,51230,50228,49288,49520,50713,48576
25,26,Iowa,58570,56247,54736,53712,52229,50957,49427,47961,48044,48980,47292
26,27,Nevada,58003,55180,52431,51450,51230,49760,48927,51001,53341,56361,55062
27,28,Vermont,57513,57677,56990,54166,52578,52997,52776,49406,51618,52104,49907
28,29,Arizona,56581,53558,51492,50068,48510,47826,46709,46789,48745,50958,49889
29,30,South Dakota,56894,54467,53017,50979,48947,48362,48321,45904,45043,46032,43424
30,31,Kansas,56422,54935,53906,52504,50972,50241,48264,48257,47817,50177,47451
31,32,Maine,56277,53079,51494,49462,46974,46709,46033,45815,45734,46581,45888
32,33,Georgia,56183,53559,51244,49321,47829,47209,46007,46430,44736,50861,49136
33,34,Michigan,54909,52492,51084,49847,48273,46859,45981,45413,45255,48591,47950
34,35,Indiana,54181,52314,50532,49446,47529,46974,46438,44613,45424,47966,47448
35,36,Ohio,54021,52334,51075,49308,48081,46829,45749,45090,45395,47988,46597
36,37,Missouri,53578,51746,50238,48363,46931,45321,45247,44301,45229,46867,45114
37,38,Montana,53386,50027,49509,46328,46972,45076,44222,42666,42322,43654,43531
38,39,North Carolina,52752,50584,47830,46556,45906,45150,43916,43326,43674,46549,44670
39,40,Florida,52594,50860,49426,47463,46036,45040,44299,44409,44736,47778,47804
40,41,Idaho,52225,51807,48275,47861,46783,45489,43341,43490,44926,47576,46253
41,42,Tennessee,51340,48547,47275,44361,44297,42764,41693,41461,41725,43614,42367
42,43,South Carolina,50570,49501,47238,45238,44163,43107,43916,42018,42442,44625,43329
43,44,Oklahoma,50051,49176,48568,47529,45690,44312,43225,42072,41664,42822,41567
44,45,Kentucky,48375,46659,44765,42958,43399,41724,41141,40062,40072,41538,40267
45,46,Alabama,48123,46257,44765,42830,42849,41574,41415,40474,40489,42666,40554
46,47,New Mexico,46744,46748,45382,44803,43872,42558,41963,42090,43028,43508,41452
47,48,Louisiana,46145,45146,45727,44555,44164,42944,41734,42505,42429,43733,40926
48,49,Arkansas,45869,45907,42798,44922,39376,39018,41302,38587,36538,39586,38134
49,50,Mississippi,43529,41754,40593,39680,37963,37095,36919,36851,36646,37790,36338
50,51,West Virginia,43469,43385,42019,41059,41253,40196,38482,37218,37435,37989,37060